// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PersonalMoney {
    
    
    public partial class MainWindow {
        
        private Gtk.UIManager UIManager;
        
        private Gtk.Action FileAction;
        
        private Gtk.Action ExitAction;
        
        private Gtk.Action ViewAction;
        
        private Gtk.Action ExpensesAction;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar2;
        
        private Gtk.Notebook notebook;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PersonalMoney.MainWindow
            this.UIManager = new Gtk.UIManager();
            Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
            this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("File"), null, null);
            this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
            w1.Add(this.FileAction, null);
            this.ExitAction = new Gtk.Action("ExitAction", Mono.Unix.Catalog.GetString("Exit"), null, null);
            this.ExitAction.ShortLabel = Mono.Unix.Catalog.GetString("Exit");
            w1.Add(this.ExitAction, null);
            this.ViewAction = new Gtk.Action("ViewAction", Mono.Unix.Catalog.GetString("View"), null, null);
            this.ViewAction.ShortLabel = Mono.Unix.Catalog.GetString("View");
            w1.Add(this.ViewAction, null);
            this.ExpensesAction = new Gtk.Action("ExpensesAction", Mono.Unix.Catalog.GetString("Expenses"), null, null);
            this.ExpensesAction.ShortLabel = Mono.Unix.Catalog.GetString("Expenses");
            w1.Add(this.ExpensesAction, null);
            this.UIManager.InsertActionGroup(w1, 0);
            this.AddAccelGroup(this.UIManager.AccelGroup);
            this.Name = "PersonalMoney.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("MainWindow");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child PersonalMoney.MainWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            // Container child vbox1.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'><menuitem name='ExitAction' action='ExitAction'/></menu><menu name='ViewAction' action='ViewAction'><menuitem name='ExpensesAction' action='ExpensesAction'/></menu></menubar></ui>");
            this.menubar2 = ((Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
            this.menubar2.Name = "menubar2";
            this.vbox1.Add(this.menubar2);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.notebook = new Gtk.Notebook();
            this.notebook.CanFocus = true;
            this.notebook.Name = "notebook";
            this.notebook.CurrentPage = -1;
            this.vbox1.Add(this.notebook);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.notebook]));
            w3.Position = 1;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 300;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.ExpensesAction.Activated += new System.EventHandler(this.OnExpensesActionActivated);
        }
    }
}
